version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kas-rusty-kaspad_web_1
      APP_PORT: 4321

  web:
    image: nginx:stable-alpine@sha256:c8fac17ccd9d570a6a5d358fca9d295895333ce1498f45c15ba5dfe88da7dfab
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_DATA_DIR}/data/web:/usr/share/nginx/html:ro

  node:
    image: supertypo/rusty-kaspad:v0.15.2@sha256:abac8e640cc2570c8d6cdf2018c8590cb1f670ea2af980daf518fe26557215a5
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - 16110:16110  # GRPC
      - 16111:16111  # P2P
      - 17110:17110  # WRPC (Borsh)
      - 18110:18110  # WRPC (JSON)