version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: elldeeone-kas-rusty-kaspad_web_1
      APP_PORT: 4321

  web:
    image: nginx:stable-alpine@sha256:b9e1705b69f778dca93cbbbe97d2c2562fb26cac1079cdea4e40d1dad98f14fe
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${APP_DATA_DIR}/data/web:/usr/share/nginx/html:ro

  node:
    image: supertypo/rusty-kaspad:v0.16.1@sha256:ed9c41fc4f9eae693ece9f2291cda55a0222a242521a74aa7cd5e40fc46aa39c
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - 16110:16110  # GRPC
      - 16111:16111  # P2P
      - 17110:17110  # WRPC (Borsh)
      - 18110:18110  # WRPC (JSON)